module.exports = {
    scene_scenes_cfg: require('./scene_scenes_cfg'),
    newweapon_weapons_cfg: require('./newweapon_weapons_cfg'),
    common_const_cfg: require('./common_const_cfg'),
    fish_fish_cfg: require('./fish_fish_cfg'),
    fish_audio_cfg: require('./fish_audio_cfg'),
    scene_tide_cfg: require('./scene_tide_cfg'),
    scene_paths_cfg: require('./scene_paths_cfg'),
    skill_skill_fish_cfg: require('./skill_skill_fish_cfg'),
    all_merge: require('./all_merge.json'),
    player_level_cfg: require('./player_level_cfg'),
    shop_fund_cfg: require('./shop_fund_cfg'),
    common_mathadjust_const_cfg: require('./common_mathadjust_const_cfg'),
    skill_skill_cfg: require('./skill_skill_cfg'),
    vip_vip_cfg: require('./vip_vip_cfg'),
    newweapon_upgrade_cfg: require('./newweapon_upgrade_cfg'),
    goddess_goddessup_cfg: require('./goddess_goddessup_cfg'),
    common_log_const_cfg: require('./common_log_const_cfg'),
    newweapon_star_cfg: require('./newweapon_star_cfg'),
    player_users_cfg: require('./player_users_cfg'),
};
