
// 4cpu02-node04.local,171.244.35.45,root,pemjsXH8Ce7E2G5j
// 4cpu01-node04.local,171.244.35.44,root,k5N6s3auYfu7tN4q
// 4cpu03-node04.local,171.244.35.43,root,Cpn3vXtsmvKuaTR9
// 4cpu01-node05.local,171.244.35.42,root,Y5A6vtHJCkpGBhQx
// 4cpu02-node05.local,171.244.35.41,root,Vg8Bd3xPEP4V8E5g
// 4cpu03-node05.local,171.244.35.40,root,YDCNcPpKrjgJ2Ka4
// 4cpu01-node06.local,171.244.35.39,root,44SqgfnJGY43gxz8
// 4cpu02-node06.local,171.244.35.38,root,YtutDgNwd3WmLHGr
// 2cpu01-node06.local,171.244.35.37,root,QA6vAB7tGD3b3SmC

// 4cpu02-node04.hongkong,119.28.176.122,root,Chufeng123456,data_server_a

// 4cpu02-node04.local,171.244.35.45,root,pemjsXH8Ce7E2G5j,balance_server
// 4cpu01-node04.local,171.244.35.44,root,k5N6s3auYfu7tN4q,chat_server
// 4cpu03-node04.local,171.244.35.43,root,Cpn3vXtsmvKuaTR9,fight_server
// 4cpu01-node05.local,171.244.35.42,root,Y5A6vtHJCkpGBhQx,fight_server
// 4cpu02-node05.local,171.244.35.41,root,Vg8Bd3xPEP4V8E5g,fight_server
// 4cpu03-node05.local,171.244.35.40,root,YDCNcPpKrjgJ2Ka4,data_server
// 4cpu01-node06.local,171.244.35.39,root,44SqgfnJGY43gxz8,data_server
// 4cpu02-node06.local,171.244.35.38,root,YtutDgNwd3WmLHGr,data_server
// 2cpu01-node06.local,171.244.35.37,root,QA6vAB7tGD3b3SmC,resource_server

const keys = ["pair:uid:rmb",
"big_data:gold:gain:box_reward:history",
"pair:uid:rank_in_friends",
"pair:uid:sid",
"pair:uid:charm_rank",
"pair:uid:drop_once",
"big_data:gold:cost:minigame:history",
"big_data:gold:gain:nuclear:history",
"pair:uid:get_card",
"pair:uid:achieve_point",
"big_data:gold:cost:other:history",
"pair:uid:charm_point",
"fishjoy:room:pumpwater",
"big_data:gold:cost:bonusdraw:history",
"pair:uid:cdkey_on",
"big_data:gold:cost:vipgift_buy:history",
"pair:uid:petfish_total_level",
"pair:uid:max_wave",
"pair:uid:cost",
"big_data:gold:cost:laser:history",
"pair:uid:gold_total_gain",
"pair:uid:skill",
"pair:uid:active",
"pair:uid:password",
"big_data:gold:cost:timegift_buy:history",
"big_data:gold:cost:active_draw:history",
"pair:uid:heartbeat_min_cost",
"big_data:gold:cost:total:history",
"chart:achieve:1",
"fishjoy:updated_uids",
"big_data:gold:cost:active_quest:history",
"pair:uid:match_box_list",
"pair:uid:first_buy",
"big_data:gold:cost:achieve_gain:history",
"pair:uid:bonus_pool",
"pair:uid:new_reward_adv",
"big_data:gold:left:total:history",
"pair:uid:charm:rank",
"pair:uid:logout_count",
"chart:charm:yesterday:string:1",
"pair:uid:diamond_total_gain",
"big_data:gold:gain:enshrine_reward:history",
"big_data:skin:vote:uid:5",
"pair:uid:exp",
"chart:achieve:2",
"pair:uid:match:season:1st_win",
"big_data:gold:cost:fire:history",
"chart:goddess:2",
"big_data:gold:gain:vipgift_buy:history",
"big_data:gold:gain:gold_shopping:history",
"pair:uid:goddess_crossover",
"pair:uid:pwd_history",
"rank:achieve:timestamp",
"big_data:gold:cost:charts_reward:history",
"pair:uid:figure",
"pair:uid:social_share_top_rank",
"pair:uid:match_points",
"pair:uid:bp",
"fishjoy:room:platformCatchRate",
"fishjoy:platform:pumpPool",
"pair:uid:social_share_status_2",
"pair:uid:city",
"account_counter",
"pair:uid:day_reward",
"pair:uid:match_season_1st_win",
"big_data:skin:vote:uid:2",
"big_data:gold:gain:card_reward:history",
"big_data:gold:gain:charts_reward:history",
"big_data:gold:gain:first_buy:history",
"pair:uid:recharge",
"pair:uid:mission_daily_reset",
"pair:uid:over_me_friends",
"big_data:gold:cost:card_reward:history",
"big_data:gold:gain:achieve_gain:history",
"big_data:gold:gain:share_reward:history",
"pair:uid:match_season_win",
"big_data:gold:gain:active_charge:history",
"pair:uid:has_social",
"rank:loss",
"pair:uid:social_invite_reward",
"pair:uid:new_player",
"big_data:gold:gain:invite_reward:history",
"pair:uid:match_box_timestamp",
"pair:uid:social_share_top_gold",
"big_data:gold:left:num:today",
"pair:uid:channel",
"pair:uid:gain_loss_snapshot",
"pair:uid:match_got_season_reward",
"big_data:gold:cost:active_charge:history",
"pair:uid:gain_loss_limit",
"pair:uid:vip_daily_fill",
"big_data:gold:gain:total:history",
"chart:charm:1",
"pair:uid:social_invite_progress",
"pair:uid:test",
"pair:uid:match_season_box",
"chart:achieve:yesterday:string:1",
"big_data:gold:gain:active_exchange:history",
"pair:openid:uid",
"pair:uid:vip_gift",
"pair:uid:vip",
"pair:uid:mail_box",
"big_data:gold:gain:laser:history",
"big_data:gold:gain:month_sign_reward:history",
"big_data:gold:gain:fire:history",
"big_data:gold:left:num:history",
"big_data:gold:cost:enshrine_reward:history",
"rank:charm:timestamp",
"pair:uid:match:season:count",
"pair:uid:match_on",
"pair:uid:pirate",
"pair:uid:cik_on",
"pair:uid:channel_account_id",
"pair:uid:vip_fill_this_time",
"pair:uid:package",
"pair:uid:weapon_skin",
"pair:uid:heartbeat",
"chart:match:yesterday:string:1",
"pair:uid:free_draw",
"pair:uid:goddess",
"pair:uid:channel_account_info",
"pair:uid:charm:point",
"chart:match:3",
"msg:private_297",
"pair:uid:first_login",
"pair:uid:social_share_status_1",
"pair:uid:figure_url",
"pair:uid:player_catch_rate",
"pair:uid:gold_total_cost",
"pair:uid:redress_no",
"pair:uid:nickname",
"fishjoy:platfrom:pumpPool",
"fishjoy:platform:today_cash",
"pair:uid:match_rank",
"fishjoy:platform:totalGold",
"pair:uid:platform",
"pair:uid:who_share_me",
"big_data:gold:gain:petfish_upgrade:history",
"big_data:gold:cost:daily_gain:history",
"pair:uid:vip_daily_reward",
"pair:uid:diamond_shop_count",
"pair:uid:level_mission",
"pair:uid:sex",
"pair:uid:login_count",
"big_data:gold:gain:bonusdraw:history",
"fishjoy:platfrom:bonusPool",
"big_data:gold:gain:other:history",
"pair:uid:created_at",
"pair:uid:social_invite_friends",
"chart:match:yesterday:1",
"pair:uid:weapon_energy",
"pair:uid:level",
"pair:uid:weapon",
"pair:uid:updated_at",
"pair:uid:gold_shop_amount",
"pair:uid:match_1st_box",
"pair:uid:last_online_time",
"pair:uid:goddess_ctimes",
"pair:uid:broke_times",
"rank:bp:timestamp",
"pair:uid:drop_reset",
"chart:charm:yesterday:1",
"pair:uid:updated_uids",
"pair:uid:week_rank",
"chart:bp:yesterday:1",
"pair:uid:card",
"pair:uid:social_enshrine_status",
"pair:uid:pfft_at",
"pair:uid:guide",
"rank:match:1",
"pair:uid:active_daily_reset",
"pair:uid:diamond_total_cost",
"pair:uid:online_time",
"pair:uid:match_recent_time",
"pair:uid:mission_only_once",
"pair:uid:match:season:box",
"big_data:gold:cost:share_reward:history",
"pair:uid:match_win",
"big_data:skin:vote:uid",
"pair:uid:channel_account_name",
"pair:uid:match_unfinish",
"fishjoy:platform:give",
"pair:uid:who_invite_me",
"fishjoy:platform:cash",
"rank:bp:1",
"pair:uid:total_draw",
"pair:uid:active_stat_reset",
"pair:uid:match_fail",
"pair:uid:month_sign",
"msg:askfriend_293",
"pair:uid:tempname",
"pair:uid:pump_pool",
"pair:uid:first_buy_gift",
"pair:uid:match_winning_streak",
"pair:uid:gain_loss",
"pair:uid:gold",
"pair:uid:free_goddess",
"pair:uid:goddess_ongoing",
"pair:uid:active_stat_once",
"global:switch:cik",
"chart:match:1",
"pair:uid:match_season_count",
"pair:uid:comeback",
"pair:uid:game_friend",
"rank:gain",
"pair:uid:aquarium",
"pair:uid:pearl",
"chart:bp:yesterday:string:1",
"pair:uid:activity_gift",
"chart:bp:1",
"rank:achieve:1",
"pair:uid:goddess_free",
"pair:uid:day_reward_adv",
"big_data:gold:cost:invite_reward:history",
"rank:charm:1",
"big_data:gold:cost:active_exchange:history",
"cache:uid_tobe_stored",
"big_data:gold:cost:nuclear:history",
"big_data:gold:cost:gold_shopping:history",
"big_data:gold:cost:first_buy:history",
"pair:uid:social_invite_daily_state",
"pair:uid:gold_shop_count",
"pair:uid:msgboard_mgmt",
"big_data:gold:gain:fund_buy:history",
"chart:achieve:yesterday:1",
"pair:uid:need_insert",
"pair:uid:petfish_recent_time",
"pair:uid:match:season:win",
"big_data:gold:cost:box_reward:history",
"msg:private_293",
"pair:uid:roipct_time",
"pair:uid:cash",
"pair:uid:token",
"pair:uid:gold_shopping",
"pair:uid:guide_weak",
"big_data:gold:cost:petfish_upgrade:history",
"fishjoy:platform:recharge",
"pair:uid:jointype",
"pair:uid:vip_weapon_id",
"pair:uid:social_share_friends",
"pair:uid:horn_used",
"big_data:gold:gain:timegift_buy:history",
"pair:uid:week_reward",
"updated_uids",
"pair:uid:playerCatchRate",
"big_data:gold:gain:active_draw:history",
"pair:uid:salt",
"big_data:gold:cost:fund_buy:history",
"fishjoy:platform:bonusPool",
"pair:uid:bonus",
"pair:uid:goddess_balance_time",
"pair:uid:openid",
"big_data:gold:gain:daily_gain:history",
"chart:match:2",
"big_data:gold:left:total:today",
"pair:uid:id",
"pair:uid:need_update",
"big_data:gold:cost:month_sign_reward:history",
"pair:uid:day_reward_weekly",
"pair:uid:social_share_status_0",
"big_data:gold:gain:minigame:history",
"chart:goddess:1",
"pair:uid:diamond_shop_amount",
"big_data:gold:gain:active_quest:history"];


function deleteAllKey(){
    keys.forEach(function(item){
        redisConnector.cmd.del(item);
    });
    console.log('删除key败');
}

module.exports.deleteAllKey = deleteAllKey;


 